'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.RadFilter
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Main
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.RadFilter.Main", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Expression.
        '''</summary>
        Friend Shared ReadOnly Property AddExpressionToolTip() As String
            Get
                Return ResourceManager.GetString("AddExpressionToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Group.
        '''</summary>
        Friend Shared ReadOnly Property AddGroupToolTip() As String
            Get
                Return ResourceManager.GetString("AddGroupToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend Shared ReadOnly Property ApplyButtonText() As String
            Get
                Return ResourceManager.GetString("ApplyButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to And.
        '''</summary>
        Friend Shared ReadOnly Property BetweenDelimeterText() As String
            Get
                Return ResourceManager.GetString("BetweenDelimeterText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Between.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionBetween() As String
            Get
                Return ResourceManager.GetString("FilterFunctionBetween", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contains.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionContains() As String
            Get
                Return ResourceManager.GetString("FilterFunctionContains", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DoesNotContain.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionDoesNotContain() As String
            Get
                Return ResourceManager.GetString("FilterFunctionDoesNotContain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EndsWith.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionEndsWith() As String
            Get
                Return ResourceManager.GetString("FilterFunctionEndsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EqualTo.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionEqualTo() As String
            Get
                Return ResourceManager.GetString("FilterFunctionEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GreaterThan.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionGreaterThan() As String
            Get
                Return ResourceManager.GetString("FilterFunctionGreaterThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GreaterThanOrEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionGreaterThanOrEqualTo() As String
            Get
                Return ResourceManager.GetString("FilterFunctionGreaterThanOrEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IsEmpty.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionIsEmpty() As String
            Get
                Return ResourceManager.GetString("FilterFunctionIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IsNull.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionIsNull() As String
            Get
                Return ResourceManager.GetString("FilterFunctionIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LessThan.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionLessThan() As String
            Get
                Return ResourceManager.GetString("FilterFunctionLessThan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LessThanOrEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionLessThanOrEqualTo() As String
            Get
                Return ResourceManager.GetString("FilterFunctionLessThanOrEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NotBetween.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionNotBetween() As String
            Get
                Return ResourceManager.GetString("FilterFunctionNotBetween", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NotEqualTo.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionNotEqualTo() As String
            Get
                Return ResourceManager.GetString("FilterFunctionNotEqualTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NotIsEmpty.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionNotIsEmpty() As String
            Get
                Return ResourceManager.GetString("FilterFunctionNotIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NotIsNull.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionNotIsNull() As String
            Get
                Return ResourceManager.GetString("FilterFunctionNotIsNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to StartsWith.
        '''</summary>
        Friend Shared ReadOnly Property FilterFunctionStartsWith() As String
            Get
                Return ResourceManager.GetString("FilterFunctionStartsWith", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to And.
        '''</summary>
        Friend Shared ReadOnly Property GroupOperationAnd() As String
            Get
                Return ResourceManager.GetString("GroupOperationAnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not And.
        '''</summary>
        Friend Shared ReadOnly Property GroupOperationNotAnd() As String
            Get
                Return ResourceManager.GetString("GroupOperationNotAnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Or.
        '''</summary>
        Friend Shared ReadOnly Property GroupOperationNotOr() As String
            Get
                Return ResourceManager.GetString("GroupOperationNotOr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Or.
        '''</summary>
        Friend Shared ReadOnly Property GroupOperationOr() As String
            Get
                Return ResourceManager.GetString("GroupOperationOr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Between.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderBetweenText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderBetweenText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contains.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderContainsText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderContainsText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Does Not Contain.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderDoesNotContainText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderDoesNotContainText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ends With.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderEndsWithText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderEndsWithText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to =.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderEqualToText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderEqualToText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &gt;=.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderGreaterThanOrEqualToText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderGreaterThanOrEqualToText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &gt;.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderGreaterThanText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderGreaterThanText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Empty.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderIsEmptyText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderIsEmptyText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Null.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderIsNullText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderIsNullText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;=.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderLessThanOrEqualToText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderLessThanOrEqualToText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderLessThanText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderLessThanText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NotBetween.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderNotBetweenText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderNotBetweenText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;&gt;.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderNotEqualToText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderNotEqualToText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Not Empty.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderNotIsEmptyText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderNotIsEmptyText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Not Null.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderNotIsNullText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderNotIsNullText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starts With.
        '''</summary>
        Friend Shared ReadOnly Property PreviewProviderStartsWithText() As String
            Get
                Return ResourceManager.GetString("PreviewProviderStartsWithText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Item.
        '''</summary>
        Friend Shared ReadOnly Property RemoveToolTip() As String
            Get
                Return ResourceManager.GetString("RemoveToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please do not remove this key..
        '''</summary>
        Friend Shared ReadOnly Property ReservedResource() As String
            Get
                Return ResourceManager.GetString("ReservedResource", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
